### ISSUE TITLE
Lexica dump files

### ISSUE THREAD

**Issue by eware-godaddy** [sharonzhou/long_stable_diffusion#3]
Thanks for sharing this amazing project.

I was wondering how to download/generate the lexica data dump CSVs that are referenced in your code. I'm also trying to build some projects out that leverage this data, and was wondering what the best way to get samples of this data would be.

Thanks for the great work, and for sharing this with the communty!

**Comment by Jeremy-Fuller** [comment]
[[]](https://github.com/Jeremy-Fuller/LexicaData/releases/tag/v1.0.0)(url)

**Comment by eware-godaddy** [comment]
Thank you!

**Comment by sharonzhou** [comment]
Thanks :)

https://github.com/Jeremy-Fuller/LexicaData/releases/tag/v1.0.0
